### ISSUE TITLE
DI Mode with less requests/network use

### ISSUE THREAD

**Issue by chiola04** [psouza4/EKUnleashed#10]
A recent update to EK has made it so a network can be denied access to EK for a period of time if too many requests have been made within a certain time frame. It is fine if you are using EKU one account on one server, but two will trigger it during DI. Is it possible to have a lite mode for DI? I am not familiar with how EKU works, but things like Demon HP or the top 10 leaderboard aren't necesarilly required and could be disabled in lite mode.

**Comment by fyreflow** [comment]
Is that what is going on? It's been driving me nuts.

Other things I have found that will trigger it:
- buying with FTs on more than one account
- exploring on more than one account at the same time

**Comment by fyreflow** [comment]
In fact, I'm having problems at almost any daily event time, such as:
- Ranked Matches after server reset
- DI
- After DI (energy spend)
- KW
- After KW (energy spend)

It seems to me that this problem will only be solved by somehow inserting randomised "cooldowns" for EKU to use before executing certain things, so that everything doesn't happen simultaneously.

**Comment by psouza4** [comment]
This was resolved with release 2.09 by adding various throttling and networking improvements.
