### ISSUE TITLE
Website down, Login failures result

### ISSUE THREAD

**Issue by fyreflow** [psouza4/EKUnleashed#14]
EKU can't be started up because, apparently, the www.ekunleashed.com website it not functioning:

![eku error](https://cloud.githubusercontent.com/assets/16628978/15499490/d0f387c4-21a4-11e6-822f-82ce39cbf05b.PNG)
![eku error 2](https://cloud.githubusercontent.com/assets/16628978/15499514/e295c3fc-21a4-11e6-8650-f9642cfa74f4.PNG)

Is it really still necessary for EKU to link up with the website now that licensing components have been removed?

Already-logged-in copies of EKU is functioning normally in this time.

**Comment by fyreflow** [comment]
![eku error 3](https://cloud.githubusercontent.com/assets/16628978/15499731/fbe06032-21a5-11e6-9b52-3ea8572d0d3d.PNG)

**Comment by psouza4** [comment]
This has been asked and answered before -- it's connecting to the server to
validate server time since we have a large percentage of users in
international time zones that don't understand US daylight savings time.
I've been asked before to have backup methods of determining the time and
I'm more than welcome to the idea if someone wants to add it -- the project
_IS_ open source.

On Tue, May 24, 2016 at 3:52 AM, fyreflow notifications@github.com wrote:

> [image: eku error 3]
> https://cloud.githubusercontent.com/assets/16628978/15499731/fbe06032-21a5-11e6-9b52-3ea8572d0d3d.PNG
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/psouza4/EKUnleashed/issues/14#issuecomment-221220932

## 

-Pete

**Comment by psouza4** [comment]
Will use a backup site for time sync in the next version.
