### ISSUE TITLE
DI server requests

### ISSUE THREAD

**Issue by mmartin25** [psouza4/EKUnleashed#2]
It appears that during Demon Invasions, the server is hit every 1/4 second with a request to refresh Demon health and Ranking stats. Might this be contributing to the server failures and / or could it be increased to something that creates less traffic to the servers? Perhaps a randomized interval of 2-5 seconds for requests to spread out the traffic?

**Comment by psouza4** [comment]
This is true ONLY for the last 4 seconds before a CD expires so that the CD isn't missed.  For example, a 40-second cooldown would be 36 seconds of waiting without any DI-specific server requests at all and then a bunch right before the CD expires.  With the lag some people get to the server, often times a CD is over seconds before it actually should be.

Additionally, in no way can extra EKU traffic be responsible for server hardware failure causing data loss.  At the very worst, network congestion can cause service interruptions similar to a DDoS attack, if the game servers aren't prepared to handle extra traffic.  However, the amount of traffic generated exclusively from EKU users is likely barely significant compared to the regular traffic generated across all players.
